[package]
name = "dynamodb-tools"
version = "0.3.5"
edition = "2021"
license = "MIT"
documentation = "https://docs.rs/dynamodb-tools"
repository = "https://github.com/tyrchen/dynamodb-tools"
homepage = "https://github.com/tyrchen/dynamodb-tools"
description = """
A simple library to work with dynamodb local easy.
"""
readme = "README.md"
categories = ["development-tools"]
keywords = [ "aws-sdk", "dynamodb", "testing"]

[features]
default = ["connector"]
connector = [ "aws-config", "tokio", "xid"]

[dependencies]
anyhow = "1.0.68"
aws-config = { version = "0.54.1", optional = true }
aws-sdk-dynamodb = "0.24.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_yaml = "0.9.17"
tokio = { version = "1.25.0", features = ["macros", "rt", "rt-multi-thread"], optional = true }
xid = { version = "1.0.3", optional = true }
