[package]
name = "dynamodb-tester"
version = "0.2.0"
edition = "2021"
license = "MIT"
documentation = "https://docs.rs/dynamodb-tester"
repository = "https://github.com/tyrchen/dynamodb-tester"
homepage = "https://github.com/tyrchen/dynamodb-tester"
description = """
A simple library to make the test your code against dynamodb local easy.
"""
readme = "README.md"
categories = ["development-tools::testing"]
keywords = [ "aws-sdk", "dynamodb", "testing"]

[features]
default = ["local"]
local = ["anyhow", "aws-config", "serde", "serde_yaml", "tokio", "xid"]

[dependencies]
anyhow = { version = "1.0.66", optional = true }
aws-config = { version = "0.51.0", optional = true }
aws-sdk-dynamodb = { version = "0.21.0" }
serde = { version = "1.0.149", features = ["derive"], optional = true }
serde_yaml = { version = "0.9.14", optional = true }
tokio = { version = "1.23.0", features = ["macros", "rt", "rt-multi-thread"], optional = true }
xid = { version = "1.0.3", optional = true }
